"""Bounded, in-memory execution of a Vora dependency graph.

Provider callables must be thread-safe and enforce their own I/O timeout.
An in-flight provider call cannot be forcibly cancelled by this executor.
"""
from __future__ import annotations

from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from dataclasses import dataclass
import re
import threading
import time
import uuid
from typing import Callable

from .model import Workflow


class ExecutionError(Exception):
    """Workflow failure, with content-free execution events for inspection."""

    def __init__(self, message: str, *, events: list[dict] | None = None):
        super().__init__(message)
        self.events = events if events is not None else []


class TransientProviderError(ExecutionError):
    """A provider failure eligible for the runtime's bounded retry policy."""


class _RuntimeFailure(ExecutionError):
    """Known content-free errors generated by the executor itself."""


@dataclass(frozen=True)
class RunResult:
    outputs: dict[str, str]
    result: str
    events: list[dict]


_PLACEHOLDER = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")


def run(workflow: Workflow, input_text: str, provider: Callable, *,
        max_workers: int = 4, retries: int = 0, max_calls: int = 20,
        on_event: Callable[[dict], None] | None = None) -> RunResult:
    """Run all graph steps, returning the declared output.

    ``max_calls`` counts every attempted provider invocation, including retries.
    Only TransientProviderError is retried. Observer exceptions are ignored;
    observers should return quickly. No prompt or result text enters events.
    """
    start = time.monotonic()
    run_id = uuid.uuid4().hex
    events: list[dict] = []
    event_lock = threading.Lock()
    call_lock = threading.Lock()
    aborted = threading.Event()
    calls = 0

    def emit(kind: str, *, since: float | None = None, **fields) -> None:
        item = {"event": kind, "workflow": workflow.name, "run_id": run_id,
                "duration_ms": round((time.monotonic() - (start if since is None else since)) * 1000, 3),
                **fields}
        with event_lock:
            events.append(item)
            if on_event is not None:
                try:
                    on_event(dict(item))
                except Exception:
                    pass

    try:
        for name, value, minimum in (("max_workers", max_workers, 1),
                                     ("retries", retries, 0), ("max_calls", max_calls, 1)):
            if type(value) is not int or value < minimum:
                raise ExecutionError(f"{name} must be an integer >= {minimum}.")
        if not isinstance(input_text, str):
            raise ExecutionError("Workflow input must be text.")
        if not callable(provider):
            raise ExecutionError("Provider must be callable.")
        steps = {step.name: step for step in workflow.steps}
        if not steps or len(steps) != len(workflow.steps):
            raise ExecutionError("Workflow needs unique, non-empty steps.")
        if workflow.output not in steps:
            raise ExecutionError("Workflow output must name a step.")
        if workflow.input_name in steps:
            raise ExecutionError("Workflow input cannot share a step name.")
        for step in workflow.steps:
            if step.agent not in workflow.agents:
                raise ExecutionError(f"Unknown agent for step '{step.name}'.")
            refs = set(_PLACEHOLDER.findall(step.prompt)) - {workflow.input_name}
            if refs != set(step.dependencies) or not refs.issubset(steps):
                raise ExecutionError(f"Invalid dependencies for step '{step.name}'.")
        visited: set[str] = set()
        while len(visited) < len(steps):
            ready = {s.name for s in workflow.steps
                     if s.name not in visited and set(s.dependencies).issubset(visited)}
            if not ready:
                raise ExecutionError("Workflow contains a dependency cycle.")
            visited.update(ready)
        if len(steps) > max_calls:
            raise ExecutionError("Call limit is smaller than the workflow's minimum call count.")

        outputs: dict[str, str] = {}

        def execute(step, prompt: str) -> str:
            nonlocal calls
            step_start = time.monotonic()
            for attempt in range(1, retries + 2):
                try:
                    with call_lock:
                        if aborted.is_set():
                            raise _RuntimeFailure("Workflow execution was stopped.")
                        if calls >= max_calls:
                            raise _RuntimeFailure("Provider call limit reached.")
                        calls += 1
                    emit("step_started", since=step_start, step=step.name, attempt=attempt)
                    response = provider(role=workflow.agents[step.agent].role, prompt=prompt)
                    if not isinstance(response, str) or not response.strip():
                        raise _RuntimeFailure("Provider returned an empty or non-text result.")
                    emit("step_completed", since=step_start, step=step.name, attempt=attempt)
                    return response
                except TransientProviderError:
                    if attempt <= retries and not aborted.is_set():
                        emit("step_retry", since=step_start, step=step.name, attempt=attempt,
                             next_attempt=attempt + 1)
                        aborted.wait(min(0.05 * 2 ** min(attempt - 1, 5), 1.0))
                        continue
                    aborted.set()
                    emit("step_failed", since=step_start, step=step.name, attempt=attempt,
                         error_type="TransientProviderError")
                    raise ExecutionError(f"Step '{step.name}' exhausted transient retries.") from None
                except Exception as exc:
                    aborted.set()
                    emit("step_failed", since=step_start, step=step.name, attempt=attempt,
                         error_type=type(exc).__name__)
                    # Third-party exceptions may contain prompts or credentials.
                    if isinstance(exc, _RuntimeFailure):
                        raise ExecutionError(f"Step '{step.name}' failed: {exc}") from None
                    raise ExecutionError(f"Step '{step.name}' failed ({type(exc).__name__}).") from None
            raise AssertionError("unreachable")

        pending = dict(steps)
        running = {}
        with ThreadPoolExecutor(max_workers=max_workers, thread_name_prefix="vora") as executor:
            while pending or running:
                if not aborted.is_set():
                    for name, step in list(pending.items()):
                        if len(running) >= max_workers:
                            break
                        if set(step.dependencies).issubset(outputs):
                            values = {workflow.input_name: input_text, **outputs}
                            prompt = _PLACEHOLDER.sub(lambda m: values[m.group(1)], step.prompt)
                            running[executor.submit(execute, step, prompt)] = name
                            del pending[name]
                if not running:
                    raise ExecutionError("Workflow could not make progress.")
                done, _ = wait(running, return_when=FIRST_COMPLETED)
                failures = []
                for future in sorted(done, key=lambda f: running[f]):
                    name = running.pop(future)
                    try:
                        outputs[name] = future.result()
                    except Exception as exc:
                        failures.append(exc)
                if failures:
                    aborted.set()
                    for future in running:
                        future.cancel()
                    raise failures[0]
        emit("workflow_completed", calls=calls)
        return RunResult(outputs=dict(outputs), result=outputs[workflow.output], events=list(events))
    except Exception as exc:
        aborted.set()
        emit("workflow_failed", calls=calls, error_type=type(exc).__name__)
        if isinstance(exc, ExecutionError):
            exc.events = list(events)
            raise
        raise ExecutionError(f"Workflow failed ({type(exc).__name__}).", events=list(events)) from None
